baseURL = "https://blog.bryan-chu.com/"
languageCode = "en-us"
title = "Bryan's RC Blog"
theme = "beautifulhugo"

[Params]
  subtitle = "Bryan Chu's Recurse Center Adventures"
  logo = "img/rc_logo.png"
  favicon = "img/github_profile_pic.png"
